### ISSUE TITLE
1.2.4 regression with offline updates/upgrades

### ISSUE THREAD

**Issue by mcrha** [PackageKit/PackageKit#504]
The https://github.com/PackageKit/PackageKit/commit/9b7e083cf849c4ed4d66fe32250f1615ab577d94 causes a regression in offline upgrades, as reported here: https://bugzilla.redhat.com/show_bug.cgi?id=2002609

The user should be asked for the root credentials when changing offline updates/upgrades, but he/she is not asked for them. The PkOffline API doesn't have any flag for the interactivity, but it also doesn't make much sense here, because these offline updates/upgrades always require the credentials.

**Comment by pwithnall** [comment]
The fix here is to add an interactive flag to the PkOffline API and propagate it to polkit, not to assume that all callers of that code will always want user interaction. Some systems may configure their polkit rules differently so that offline updates don’t need admin authorisation. Other callers of these code paths in `pk-engine.c` (written in future?) may not want user interaction.

**Comment by mcrha** [comment]
> Some systems may configure their polkit rules differently so that offline updates don’t need admin authorisation. Other callers of these code paths in `pk-engine.c` (written in future?) may not want user interaction.

How does for example gnome-software know that? It currently sets the interactive flag for its job structure.

**Comment by pwithnall** [comment]
> How does for example gnome-software know that? It currently sets the interactive flag for its job structure.

Not sure I understand what you’re referring to. gnome-software sets the interactive flag for a `GsPluginJob` if and only if the job is run from a plugin which is currently interactive (see `gs_plugin_job_set_interactive()` and `gs_plugin_interactive_inc()`). The `GsPlugin` interactivity handling could be better in gnome-software.

Or are you referring to something else?

**Comment by mcrha** [comment]
I meant, the gnome-soft sets the interactivity flag unconditionally. Your argument is that some distros may not need the polkit prompt, but in that case the gnome-software should not set the interactivity flag, otherwise the user would be asked for the root credentials pointlessly. Thus there should be some way to know when the prompt makes sense and when not, thus when the gnome-software should have set interactivity flag and when not.

**Comment by pwithnall** [comment]
> Your argument is that some distros may not need the polkit prompt, but in that case the gnome-software should not set the interactivity flag, otherwise the user would be asked for the root credentials pointlessly

That is incorrect. If the polkit rules are set up by the distro to not require admin authorisation, a prompt will not be displayed even if interactive=True.

The value of the interactive flag should be independent of what the polkit rules are. It’s entirely dependent on the calling context — whether the polkit check is being done in the context of a user interaction, or whether it’s being done in the background. PackageKit can’t know that, as it can be called by UIs or by background services, so it can’t hardcode the allow user interaction flag (as true *or* false).



> The fix here is to add an interactive flag to the PkOffline API and propagate it to polkit, not to assume that all callers of that code will always want user interaction.

Looking more closely at the context, I was wrong to suggest this. `PkOffline` is actually already reading the user interaction flag correctly from the D-Bus call.

I think the fix is actually to ensure gnome-software (or whatever component is triggering PackageKit here) sets the `G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` flag in the D-Bus call it makes to this PackageKit API.

If that call is being made by gnome-software, it’s likely that the `GsPluginJob.interactive` property needs to be set to `TRUE` for the job that’s triggering this.

**Comment by mcrha** [comment]
The gnome-software calls just this:
```
    pk_offline_trigger_upgrade (PK_OFFLINE_ACTION_REBOOT, cancellable, error);
```
as shown here: https://gitlab.gnome.org/GNOME/gnome-software/-/blob/main/plugins/packagekit/gs-plugin-systemd-updates.c#L320

**Comment by pwithnall** [comment]
OK. `pk_offline_trigger_upgrade()` is just a wrapper around the `org.freedesktop.PackageKit.Offline.TriggerUpgrade()` D-Bus method.

How about:
 1. Adding a new `pk_offline_trigger_upgrade_with_flags()` method to PackageKit, which takes some flags, one of which is equivalent to `G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` and which sets that flag on the D-Bus call.
 2. Changing gnome-software to call that method if the PackageKit dependency is suitably new, and
 3. If the PackageKit dependency is not new enough to have `pk_offline_trigger_upgrade_with_flags()`, gnome-software could hardcode the `g_dbus_connection_call_sync()` call to `TriggerUpgrade`, and correctly pass `G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` to it if `gs_plugin_has_flags (plugin, GS_PLUGIN_FLAGS_INTERACTIVE)` is true.

The fallback changes in gnome-software should fix the bug for this cycle (assuming the interactive flag is correctly propagated within packagekitd, which it looks like it should be, as per the current code in `pk-engine.c`), and the switch to `pk_offline_trigger_upgrade_with_flags()` is the correct fix in the long term.

Does that make sense, or have I misunderstood?

**Comment by mcrha** [comment]
Yes, it makes sense. You might also know about https://bugzilla.redhat.com/show_bug.cgi?id=2003365 , which is closely related.
