### ISSUE TITLE
"offline-update-competed" or "offline-update-completed"?

### ISSUE THREAD

**Issue by msbit** [PackageKit/PackageKit#536]
The path:

    /var/lib/PackageKit/offline-update-competed

is referred to at the following locations:

* https://github.com/PackageKit/PackageKit/blob/9339249866d44f06d713e92f2abf90b470b5deb3/docs/offline-updates.txt#L31
* https://github.com/PackageKit/PackageKit/blob/9339249866d44f06d713e92f2abf90b470b5deb3/docs/offline-updates.txt#L76
* https://github.com/PackageKit/PackageKit/blob/9339249866d44f06d713e92f2abf90b470b5deb3/lib/packagekit-glib2/pk-offline-private.h#L54

Based on how it's used, it might make more sense for it to be:

    /var/lib/PackageKit/offline-update-completed

**Comment by ximion** [comment]
Haha, yeah, that's a known issue. I'm pretty sure fixing this would create an API break, that's why we never did it (I *totally* would have in the early days, but @hughsie wouldn't :-P - I faintly recall that this was spotted very early and also discussed).
This may be a `creat()` situation, but for PackageKit (damn you Ken Thompson, I always type create and then hit backspace because my mind works that way, apparently :-D).
That said, given the low amount of stuff that relies on this name, it *probably* could be fixed without breaking the world, but it would take a while (likely years).

**Comment by hughsie** [comment]
> it might make more sense for it to be:
> /var/lib/PackageKit/offline-update-completed

Unfortunately it's now API, like @ximion says. Sorry world, mea culpa.

**Comment by msbit** [comment]
@ximion @hughsie yep, very much understood. I'll close this off ✌️
