### ISSUE TITLE
Documentation of device-rebind policy is incorrect

### ISSUE THREAD

**Issue by mcatanzaro** [PackageKit/PackageKit#567]
I see in org.freedesktop.packagekit.policy.in:

```
  <action id="org.freedesktop.packagekit.device-rebind">
    <!-- SECURITY:
          - Normal users require admin authentication to rebind a driver
            so that it works after we install firmware.
          - This should not be set to 'yes' as unprivileged users could then
            try to rebind drivers in use, for instance security authentication
            devices.
     -->
    <description>Reload a device</description>
    <message>Authentication is required to reload the device with a new driver</message>
    <icon_name>package-x-generic</icon_name>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/sbin/pk-device-rebind</annotate>
  </action>
```

Well that's not right. Comment says "This should not be set to 'yes'," but it is.

**Comment by hughsie** [comment]
I don't think we use this any more. Can we rip it out or does it constitute effective ABI/API?

**Comment by mcatanzaro** [comment]
No clue. I don't know what this is.

**Comment by hughsie** [comment]
@ximion i can rip this out if you think it's a good idea.

**Comment by ximion** [comment]
I think anything that would possibly use it (and a quick search in the Debian archive via https://codesearch.debian.net/search?q=org.freedesktop.packagekit.device-rebind&literal=1 and GitHub yielded nothing) will already have been broken, so IMHO removing this is definitely fine - I don't even think this is any kind of API/ABI break, as only the packagekit daemon would use this interface directly, and any PolKit rules will just continue to work anway.
So, +1 from me for just ripping it out (I actually wonder since when we stopped using this, must have been ages ago...)
