### ISSUE TITLE
Runs destructive *full-upgrade* operation possibly breaking system

### ISSUE THREAD

**Issue by paulmenzel** [PackageKit/PackageKit#583]
Using Debian sid/unstable with *packagekit* 1.2.5-3+b1 and *gnome-software* 43.0-2, packagekit run the destructive operation equivalent to *full-upgrade* removing necessary packages like the PDF viewer Evince.

    Start-Date: 2022-10-25  17:28:02
    Commandline: packagekit role='update-packages'
    Install: libgs10:amd64 (10.0.0~dfsg-4, automatic), libgs-common:amd64 (10.0.0~dfsg-4, automatic)
    Upgrade: ghostscript-x:amd64 (9.56.1~dfsg-1, 10.0.0~dfsg-4), ghostscript:amd64 (9.56.1~dfsg-1, 10.0.0~dfsg-4)
    Remove: evince-dbgsym:amd64 (43.0-1), evince:amd64 (43.0-1), dvisvgm:amd64 (2.14-1), libevdocument3-4:amd64 (43.0-1), libgs9-common:amd64 (9.56.1~dfsg-1), libevview3-3:amd64 (43.0-1), gimp:amd64 (2.10.32-1+b1), gir1.2-evince-3.0:amd64 (43.0-1), gnome-sushi:amd64 (43.0-1), libgs9:amd64 (9.56.1~dfsg-1), libspectre1:amd64 (0.2.10-1)
    End-Date: 2022-10-25  17:28:18

(Powering off the system, I was asked “by GNOME” if updates should be installed on restart, and I confirmed.)

**Comment by ximion** [comment]
This is intentional behavior - PackageKit doesn't distinguish between a partial update and a full upgrade, so we assume if the user wants to have their system updated, the mean `full-upgrade`.
Obviously we don't want this to break anything, but that is outside of the control of PackageKit - it is very much under the control of the distribution. Are you on a development version of Debian, like *unstable*? Because there, a manual upgrade is probably better. On *testing* however, you should already be pretty safe.
Also, PackageKit tells you what the update will do, so you do have the option to not upgrade if you don't like the outcome it presents. If you don't see that information, it's a failure of the GUI, not PK.

So, I'm afraid this really is a case of "unfortunate" and nothing that we can address in PackageKit. It should be dealt with by the distributor (ensure no package gets removed by accident on an update) or by the GUI (show what will be done to the user).
If this happened on a stable Debian version, it would certainly be a critical bug, but on a development version, some extra care has to be taken.
