### ISSUE TITLE
Build failure latest release, with latest appstream on KDE Neon

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [PackageKit/PackageKit#670]
Hi, I have tried to sort this out to no avail. Sorry I need help.

Relevant error:
`06:44:34 ../backends/apt/apt-job.cpp: In member function ‘void AptJob::providesMimeType(PkgList&, gchar**)’:
06:44:34 ../backends/apt/apt-job.cpp:1468:58: error: cannot convert ‘AsComponentBox*’ {aka ‘_AsComponentBox*’} to ‘GPtrArray_autoptr’ {aka ‘_GPtrArray*’} in assignment
06:44:34  1468 |         result = as_pool_get_components_by_provided_item (pool, AS_PROVIDED_KIND_MIMETYPE, values[i]);
06:44:34       |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
06:44:34       |                                                          |
06:44:34       |                                                          AsComponentBox* {aka _AsComponentBox*}`

I looked up this in source:
`    /* search for mimetypes for all values */
    for (guint i = 0; values[i] != NULL; i++) {
        g_autoptr(GPtrArray) result = NULL;

        if (m_cancel)
            break;

        result = as_pool_get_components_by_provided_item (pool, AS_PROVIDED_KIND_MEDIATYPE, values[i]);
        for (guint j = 0; j < result->len; j++) {
            const gchar *pkgname;
            AsComponent *cpt = AS_COMPONENT (g_ptr_array_index (result, j));

            /* sanity check */
            pkgname = as_component_get_pkgname (cpt);
            if (pkgname == NULL) {
                g_warning ("Component %s has no package name (it was ignored in the search).", as_component_get_data_id (cpt));
                continue;
            }

            pkg_names.push_back (pkgname);
        }
    }`

How is it getting AsComponentBox? Maybe this source needs to match? Also should'nt MEDIATYPE be MIMETYPE?
Somehow this commit in appstream seem relevant: https://github.com/ximion/appstream/commit/19c1197243cd0507cae9f53e015d91ac141684ae#diff-4a0f5fd34a5ae12fea07ed19ce5b4944afa372d0841ef4a6c0fc4a373becc46a

But really I am clueless and reaching at this point.

Full build log here:
https://build.neon.kde.org/job/jammy_unstable_backports-jammy_packagekit_bin_amd64/7/console

Any help appreciated.
Thanks,
Scarlett

**Comment by ximion** [comment]
Apparently you are using a Git snapshot of AppStream in your CI, which does make sense, as that version provides Qt6 binaries.
However, that version also breaks API and ABI. Since it's in-development and not yet released, I haven't done any adjustments on dependent components yet to work with both APIs, and I also don't want to commit anything yet until AppSream 1.0 is in feature-freeze.

If it helps you, I could however create a preliminary patch for this change, that you could use in Neon.

**Comment by ScarlettGatelyMoore** [comment]
That would be wonderful :) Thanks ximion!

**Comment by ximion** [comment]
Unrelated, but still good to know: IANA renamed MIME types to just Media types, so AppStream followed that rename fairly early, as "mediatype" seemed to be the clearer name. https://en.wikipedia.org/wiki/Media_type

**Comment by ximion** [comment]
You can try this patch ^
It's unlikely that the 1.0 API will change drastically, but I can't make any guarantees that this won't happen again until there's a release.

**Comment by ScarlettGatelyMoore** [comment]
Thank you so much ximion! The cost of living on the edge. I will try it now. Thanks again.

**Comment by mcrha** [comment]
For what it's worth, the `as_utils_install_metadata_file` is backwards incompatible with the `as_utils_install_filename`, it cannot install the `appstream-icons.tar` file. Furthermore, the `as_utils_install_metadata_file` expects the file to be `tar.gz` and to contain the icon size in the name. None of that can be done with the appstream-builder and the PackageKit does not install icons for the repo's appstream data since the move to the appstream 1.x (well, since porting to the appstream from the libappstream-glib).

I guess I'll file a new bug for this, to not have it forgotten or lost here, only not right now. This is a little heads up.

**Comment by mcrha** [comment]
> I guess I'll file a new bug for this, ...

It's the https://github.com/PackageKit/PackageKit/issues/809
