### ISSUE TITLE
AppStream metadata allow user uninstallation of PackageKit

### ISSUE THREAD

**Issue by AsciiWolf** [PackageKit/PackageKit#759]
An AppStream metainfo file was [added](https://github.com/PackageKit/PackageKit/blob/main/data/org.freedesktop.packagekit.metainfo.xml) in PackageKit v1.2.8. Unfortunately, this file causes PackageKit to show in GNOME Software, KDE Discover and other package management GUIs and allow users to click an "Uninstall" button. This fortunately does nothing in Fedora, but there may be some distributions and/or configurations that will allow this.

Please, consider reverthing the AppStream metainfo file addition until a better solution is found.

For more information see [this comment](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/870#note_2117863) in upstream GNOME Software ticket.

**Comment by AsciiWolf** [comment]
@ximion Any chance a new version of PackageKit with this fix could be released soon?

**Comment by AsciiWolf** [comment]
(If the fix works correctly. I am not 100% sure whether multiple _compulsory_for_desktop_ tags are supported.)

**Comment by sidt4** [comment]
>  I am not 100% sure whether multiple compulsory_for_desktop tags are supported.

Matt is the maintainer of PackageKit and Appstream. So, no worries :).

**Comment by ximion** [comment]
> Any chance a new version of PackageKit with this fix could be released soon?

Yes, with a bit of luck before I will be away on a trip next week, otherwise the week after. There is still some pretty nasty bugs in PK that really should be fixed before the next release happens, and @sidt4 also has a bunch of patches that I need to review - slow releases are 100% a result of me barely having any time to work on this currently, so progress is slow. Sorry for that! There will be a new release though, if it doesn't happen this month, then for sure next month :-)

**Comment by sidt4** [comment]
I would not hurry up the release especially given the lower frequency of PK releases, and the expected new fixes / commits in the coming days. It would be nice to have at least a 3 - 4 days of testing before tagging a release. And if the commit count increases soaking time would increase accordingly.

Just my opinion.
